source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HFTableCollectionBindingHelper_Example' do
  pod "HFTableCollectionBindingHelper", :path => "../"
  target 'HFTableCollectionBindingHelper_Tests' do
    inherit! :search_paths
    pod "HFTableCollectionBindingHelper", :path => "../"
  end
end

