source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HFTableCollectionBindingHelper_Example', :exclusive => true do
  pod "HFTableCollectionBindingHelper", :path => "../"
end

target 'HFTableCollectionBindingHelper_Tests', :exclusive => true do
  pod "HFTableCollectionBindingHelper", :path => "../"

  pod 'FBSnapshotTestCase'
end
